### PR TITLE
CB-13673 : Removed deprecated platforms

### PR DESCRIPTION
**Pull request by maverickmishra**
### Platforms affected
Blackberry 10, Windows Phone

### What does this PR do?
Removes deprecated plugins

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by maverickmishra** [comment]
The Readme doc mentioned support on WP8 and that is why I removed this.

**Comment by macdonst** [comment]
Let's check with @purplecabbage to see if this implementation works on Windows UWP.

**Comment by purplecabbage** [comment]
Windows IS supported, but this pr removes it.
 <platform name="windows"> <= cannot remove that, or the file that it points to.  Just update documentation.  Where it says 8.1 Metro bs, it should say windows-uwp devices ...

**Comment by purplecabbage** [comment]
also, why did you bump the version in this pr ... it seems unrelated.

**Comment by macdonst** [comment]
@purplecabbage we decided that all plugins that are removing platforms should be major releases. @maverickmishra and @surajpindoria are bumping all plugins that are being changed to the next major dev version. The version bump doesn't become official until we do a plugins release.

**Comment by purplecabbage** [comment]
Version bumps are part of the release process. That seems like a better place for this to happen. 
The release tooling already takes care of versioning afaik.

**Pull request closed without merging**
