### PR TITLE
fix(R7-9625): fix plugin for use with webpack - fixes #73

### LINKED ISSUE #73: Uncaught (in promise) ReferenceError: screen is not defined
# Bug Report

## Problem

Bildschirmfoto 2020-09-01 um 11 40 37

### What is expected to happen?

it uses `window.screen`

### What does actually happen?

this.screen is undefined

### PR DESCRIPTION
**Pull request by SunboX**
### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Review by erisu — APPROVED** [review]
Looks OK to me

**Review by timbru31 — APPROVED** [review]

**Comment by SunboX** [comment]
there seems to be an issue in cordova-parametic:
```
---------------------------------------------------------
4. Run (Jasmine) tests...
... locally
---------------------------------------------------------
cordova-paramedic: running tests locally
cordova-paramedic: Choosing Target for iOS
running:
    cordova run --list --emulator --no-telemetry --no-update-notifier
Error: Cannot read property 'trim' of undefined
TypeError: Cannot read property 'trim' of undefined
    at Object.getSimulatorModelId (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/utils/utilities.js:92:9)
    at ParamedicTargetChooser.chooseTargetForIOS (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/ParamedicTargetChooser.js:136:44)
    at ParamedicTargetChooser.chooseTarget (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/ParamedicTargetChooser.js:43:30)
    at ParamedicRunner.getCommandForStartingTests (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:427:80)
    at /Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:239:30
From previous event:
    at ParamedicRunner.runLocalTests (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:280:14)
    at ParamedicRunner.runTests (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:376:25)
    at /Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:93:29
From previous event:
    at ParamedicRunner.run (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:79:14)
    at Object.exports.run (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:502:19)
    at Object.<anonymous> (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/main.js:184:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
---------------------------------------------------------
6. Collect data and clean up
---------------------------------------------------------
Completed tests at 2:57:36 PM
Collecting logs for the devices.
It looks like there is no target to get logs from.
Uninstalling the app.
cordova-paramedic: Killing the emulator process.
Running the following command:
    killall -9 "Simulator" "iOS Simulator"
$ killall -9 "Simulator" "iOS Simulator"
No matching processes belonging to you were found
WARNING: kill command returned 1
local-server: killing local file transfer server if it's up...
cordova-paramedic: Deleting the application: /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/tmp-3781kPQL4fLQ7gi7
/Users/travis/build/apache/cordova-plugin-screen-orientation
Error: TypeError: Cannot read property 'trim' of undefined
    at /Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:99:23
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
From previous event:
    at ParamedicRunner.run (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:96:19)
    at Object.exports.run (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:502:19)
    at Object.<anonymous> (/Users/travis/.nvm/versions/node/v12.18.3/lib/node_modules/cordova-paramedic/main.js:184:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
The command "if [[ "$ADDITIONAL_TESTS_DIR" != "" ]]; then
  cd $ADDITIONAL_TESTS_DIR && npm install && npm test;
else 
  $PARAMEDIC_COMMAND --config ./pr/$PLATFORM --plugin $PARAMEDIC_PLUGIN_TO_TEST --buildName $PARAMEDIC_BUILDNAME; 
fi" exited with 1.
cache.2
store build cache
```

**Comment by erisu** [comment]
@SunboX Yes, we are aware of the paramedic issue and have been actively trying to resolve the test framework.

We will re-run the tests after we have fixed the testing framework.

**Comment by erisu** [comment]
Could you rebase this PR?

After rebasing, I think the iOS failing tests will pass again. As for the browser tests, they still failing for some other reasons.

**Comment by NiklasMerz** [comment]
Closed because of this: https://github.com/apache/cordova-plugin-screen-orientation/pull/109#issuecomment-1427941376

**Pull request closed without merging**
